In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Exam in machine learning
## Problem 1: Basic Numpy


In [ ]:
a = np.arange(start=0, stop=100, step=1)
a

In [8]:
b = np.arange(start=0, stop=100, step=10)
b

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
c = np.random.rand(10, 10)
c

array([[0.81629492, 0.28033926, 0.41113646, 0.13566938, 0.05819918,
        0.59451959, 0.12874026, 0.84181137, 0.26135688, 0.09379284],
       [0.45207367, 0.91296756, 0.59982322, 0.31545896, 0.82718068,
        0.82662813, 0.90309392, 0.69619348, 0.63667599, 0.43778415],
       [0.67295924, 0.93605583, 0.88094892, 0.73739614, 0.30449274,
        0.46305946, 0.1211687 , 0.81399157, 0.00590454, 0.52595663],
       [0.60020288, 0.6614541 , 0.73430628, 0.52339346, 0.37854249,
        0.96629343, 0.68588352, 0.76892475, 0.24642354, 0.2295479 ],
       [0.45849462, 0.73132736, 0.85580262, 0.41956303, 0.29160515,
        0.54063802, 0.8364506 , 0.12482611, 0.46795912, 0.10686432],
       [0.01480666, 0.92971404, 0.41605066, 0.32307966, 0.15940011,
        0.03849413, 0.8144902 , 0.11527343, 0.63726429, 0.37027986],
       [0.95779155, 0.96306203, 0.66336082, 0.93576065, 0.56186876,
        0.52144264, 0.32676403, 0.60579006, 0.53855311, 0.99202029],
       [0.16430679, 0.18375078, 0.5706533

In [13]:
A = np.reshape(a, (10, 10))
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [14]:
A[4,5]
#A[4,5] will show the value in this place in our 2d array.
#It first counts to 4 spots(including index 0) on the X axis, and then 5 spots(also including index 0) on the Y axis.
#This corresponds to the value 45 in our 2d array

45

In [16]:
sum(sum(c))


51.49613550356568

In [20]:
B = np.transpose(b)
B

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
A + c

array([[ 0.81629492,  1.28033926,  2.41113646,  3.13566938,  4.05819918,
         5.59451959,  6.12874026,  7.84181137,  8.26135688,  9.09379284],
       [10.45207367, 11.91296756, 12.59982322, 13.31545896, 14.82718068,
        15.82662813, 16.90309392, 17.69619348, 18.63667599, 19.43778415],
       [20.67295924, 21.93605583, 22.88094892, 23.73739614, 24.30449274,
        25.46305946, 26.1211687 , 27.81399157, 28.00590454, 29.52595663],
       [30.60020288, 31.6614541 , 32.73430628, 33.52339346, 34.37854249,
        35.96629343, 36.68588352, 37.76892475, 38.24642354, 39.2295479 ],
       [40.45849462, 41.73132736, 42.85580262, 43.41956303, 44.29160515,
        45.54063802, 46.8364506 , 47.12482611, 48.46795912, 49.10686432],
       [50.01480666, 51.92971404, 52.41605066, 53.32307966, 54.15940011,
        55.03849413, 56.8144902 , 57.11527343, 58.63726429, 59.37027986],
       [60.95779155, 61.96306203, 62.66336082, 63.93576065, 64.56186876,
        65.52144264, 66.32676403, 67.60579006

In [23]:
A * c

array([[ 0.        ,  0.28033926,  0.82227293,  0.40700815,  0.23279672,
         2.97259797,  0.77244156,  5.89267962,  2.09085507,  0.84413556],
       [ 4.52073674, 10.04264311,  7.19787869,  4.10096642, 11.58052957,
        12.39942195, 14.4495028 , 11.83528912, 11.46016778,  8.31789885],
       [13.45918485, 19.65717241, 19.38087615, 16.9601113 ,  7.30782572,
        11.57648646,  3.15038615, 21.9777724 ,  0.16532715, 15.25274224],
       [18.00608644, 20.50507725, 23.49780085, 17.27198429, 12.87044452,
        33.82026999, 24.69180689, 28.45021561,  9.36409457,  8.95236797],
       [18.33978494, 29.98442172, 35.94370991, 18.04121019, 12.83062657,
        24.32871085, 38.47672779,  5.86682738, 22.46203778,  5.23635168],
       [ 0.74033307, 47.41541623, 21.63463441, 17.12322176,  8.60760574,
         2.11717738, 45.61145141,  6.57058539, 36.96132885, 21.84651164],
       [57.46749276, 58.74678369, 41.12837098, 58.95292097, 35.95960059,
        33.89377166, 21.56642615, 40.58793384

In [24]:
np.dot(A, c)


array([[ 25.67363142,  28.85583175,  22.22965556,  20.79536226,
         21.74310415,  28.766857  ,  23.64968347,  25.64237365,
         15.14789809,  18.80601326],
       [ 82.5785346 ,  96.38980676,  78.27621299,  64.46462536,
         64.1957792 ,  91.57562916,  76.26478453,  85.2533175 ,
         49.80128906,  57.47178648],
       [139.48343778, 163.92378177, 134.32277042, 108.13388846,
        106.64845424, 154.38440133, 128.87988559, 144.86426135,
         84.45468003,  96.13755971],
       [196.38834097, 231.45775678, 190.36932785, 151.80315155,
        149.10112929, 217.19317349, 181.49498665, 204.4752052 ,
        119.108071  , 134.80333293],
       [253.29324415, 298.99173178, 246.41588528, 195.47241465,
        191.55380434, 280.00194565, 234.11008771, 264.08614905,
        153.76146198, 173.46910616],
       [310.19814733, 366.52570679, 302.46244271, 239.14167775,
        234.00647938, 342.81071782, 286.72518877, 323.6970929 ,
        188.41485295, 212.13487938],
       [36

## Problem 2: Conceptual Questions
### 1.



In machine learning we cannot know if our model is overfitting or underfitting until we test our model after training, and this is why we split our initial dataset into training and test subsets. After the training of our model, we can see if our model does better on the training set than on the test set. If our model does alot better in the training set, then our model is probably overfitting.

Now that we have diagnosed that our model is probably overfitting, lets try to fix it.

There are many different solutions here, we could try training with more data to help our model. Working with more data will help even out curves and highlight abnormalities, but won't always help.

Cross-validation is a very popular solution, where we use the same training data to train alot of mini train-test splits. in cross-validation, we use these splits to fix our model.

We could also remove some features in our model, if our model is too complex, that might be the reason it's overfitting.

The are many different techniques to regularize our model as well. Regularization is a way to tune the function by adding penalties. This reduces wrights and biases, and in turn helps to overcome overfitting. We will be looking more at regression in answer 2.

Finally, i want to mention early stopping. The amount of iterations has a big impact on the performance of our model, and there will be a certain iteration where our model takes a turn into overfitting. Up until this point the model as been working to imprve the model, but will now generalize less and start overfitting instead. Stopping the iterations here leads to stopping the models ability to overfit.

### 2.

Both LASSO and ridge regression are advantageous in avoiding overfitting

Ridge regression attemps to increase the bias to improve variance, this model performance is usually a little bad on the training set, but will perform consistently well on training and testing.

Ridge regressions penalty term reduces the slope, and therefore the model becomes less sensitive to changes in independent variables. This is what prevents overfitting. We can tune how sensitive the model is to independent variables, which makes it very powerful for a programmer. However, we must also adjust this manually, which means we end up using time testing how sensitive the model is. This can be both advantageous and disadvantegeous.

LASSO regression works kind of similar to Ridge, as a regression we still want to add a penalty term. In LASSO, we use the absolute value of the slope and bias and add that as our penalty term. LASSO is particularly useful for feature selection. LASSO is usually good if there are a small number for significant parameters, and the other parameters are close to zero.

Lasso regression reaches 0 when looking at the sum of squared residuals, Ridge will never reach zero, but can get close.

All in all the only real difference between Ridge and LASSO, is that Ridge adds the absolute values of the weights, while LASSO adds the weights squared.

In [33]:
df = pd.read_csv (r'housedata.csv', sep="\;")
df

<ipython-input-33-7d921ce5dc60>:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv (r'housedata.csv', sep="\;")


id  bedrooms  sqft_living  sqft_lot  floors  sqft_above  \
0    7129300520         3         1180      5650       1        1180   
1    6414100192         3         2570      7242       2        2170   
2    5631500400         2          770     10000       1         770   
3    2487200875         4         1960      5000       1        1050   
4    1954400510         3         1680      8080       1        1680   
..          ...       ...          ...       ...     ...         ...   
994  5147600105         2          740      6460       1         740   
995  7437100570         4         1860      6325       2        1860   
996  8856004730         2         1590     20917       1        1590   
997  3856902996         2          850      2340       1         850   
998  1442800370         2         1030      4188       1        1030   

     sqft_basement     price  
0                0  221900.0  
1              400  538000.0  
2                0  180000.0  
3              910  604000.0  
4                0  510000.0  
..             ...       ...  
994              0  178500.0  
995              0  291000.0  
996              0  199950.0  
997              0  553500.0  
998              0  189950.0  

[999 rows x 8 columns]

In [1]:
### 3.